### ISSUE TITLE
Kubernetes Job yml manifest changes 

### ISSUE THREAD

**Issue by ssathyaji** [aquasecurity/kube-hunter#366]
### What happened

When we deploy job.yml for kubernetes cluster we are facing kube-hunter.py file not found error. Need to change the job.yml file changes.

### Expected behavior

Please use the followin yml file for kubernetes cluster. 

> apiVersion: batch/v1
> kind: Job
> metadata:
>   name: kube-hunter
> spec:
>   template:
>     spec:
>       containers:
>       - name: kube-hunter
>         image: aquasec/kube-hunter
>         command: ["kube-hunter"]
>         args: ["--pod"]
>       restartPolicy: Never
>   backoffLimit: 4

**Comment by brathina-spectro** [comment]
I ran into this too with Pod deployment. 

**Job manifest Used**
```
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter 
        command: ["python", "kube-hunter.py"]
        args: ["--pod"]
      restartPolicy: Never
  backoffLimit: 4
```

**Error seen with pods scheduled** 
```
$ kcl logs kube-hunter-2m5xb
python: can't open file 'kube-hunter.py': [Errno 2] No such file or directory
```

**Comment by ramakuka** [comment]
It's probably a dirty hack, but it worked as a simple workaround until the bug will get fixed
I replaced kube-hunber.py on the command to /usr/local/bin/kube-hunter and it fixed the problem 

so the Job manifest 
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter 
        command: ["python", "/usr/local/bin/kube-hunter"]
        args: ["--pod"]
      restartPolicy: Never
  backoffLimit: 4
```
