### ISSUE TITLE
Kube-hunter vulnerability scanner Algorithm?

### ISSUE THREAD

**Issue by Al4DIN** [aquasecurity/kube-hunter#514]
## What are you trying to achieve

I'm working on an MlOps pipeline for a computer vision use case, and I'm currently deploying my bricks on kubernetes but I had the reflexion to think about my cluster security since it will be applied for image classification so I need to be sure that all my components are well configured. 
I found out kube-hunter on an online article and was a "quick win" to get most results but I had some misunderstood informations (some I found responses on issues closed and others not).

When I deployed my kube-hunter job as a passive test, I was wondering what type of algorithm or concept behind this "small simple" job? I tried to look on documentation or the repo but I didnt find enough infos or hints.

## Minimal example (if applicable)
This is the job that I used, I also tried to fine tune the arguments so I can test multiple functionalities.

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  template:
    metadata:
      labels:
        app: kube-hunter
    spec:
      containers:
        - name: kube-hunter
          image: aquasec/kube-hunter:0.6.8
          command: ["kube-hunter"]
          args: ["--pod"]
      restartPolicy: Never
```
